### ISSUE TITLE
Luarocks package?

### ISSUE THREAD

**Issue by Frityet** [javalikescript/luajls#1]
I was wondering if this project would ever get posted on luarocks, the lua package manager

**Comment by javalikescript** [comment]
Hello,
Well, yes and no, there is a base package with only Lua dependencies so it should work anywhere but does not provide network or file system APIs.
Based on this package there are full packages one using luasocket, lfs, the other using luv but having native dependencies the installation is pretty difficult. You will find the packages here https://luarocks.org/modules/javalikescript
There is currently no good integration with luarocks, so depending on your needs, I would recommend to grab the binaries or to build the luaclibs project here https://github.com/javalikescript/luaclibs.
Have a good day,
Samuel

**Comment by Frityet** [comment]
Thank you!
